<?php

namespace Emaia\LaravelHotwire\Support;

use Emaia\LaravelHotwire\Components;

final class ComponentAliases
{
    /** @return array<string, class-string> */
    public static function subComponents(): array
    {
        return [
            'accordion.item' => Components\Accordion\Item::class,
            'accordion.trigger' => Components\Accordion\Trigger::class,
            'accordion.content' => Components\Accordion\Content::class,
            'modal.header' => Components\Modal\Header::class,
            'modal.title' => Components\Modal\Title::class,
            'modal.description' => Components\Modal\Description::class,
            'modal.content' => Components\Modal\Content::class,
            'modal.footer' => Components\Modal\Footer::class,
            'alert-dialog.header' => Components\AlertDialog\Header::class,
            'alert-dialog.title' => Components\AlertDialog\Title::class,
            'alert-dialog.description' => Components\AlertDialog\Description::class,
            'alert-dialog.content' => Components\AlertDialog\Content::class,
            'alert-dialog.footer' => Components\AlertDialog\Footer::class,
            'alert.action' => Components\Alert\Action::class,
            'alert.description' => Components\Alert\Description::class,
            'alert.title' => Components\Alert\Title::class,
            'avatar.image' => Components\Avatar\Image::class,
            'avatar.fallback' => Components\Avatar\Fallback::class,
            'avatar.badge' => Components\Avatar\Badge::class,
            'avatar.group' => Components\Avatar\AvatarGroup::class,
            'avatar.group-count' => Components\Avatar\GroupCount::class,
            'button-group.separator' => Components\ButtonGroup\Separator::class,
            'button-group.text' => Components\ButtonGroup\Text::class,
            'breadcrumb.list' => Components\Breadcrumb\BreadcrumbList::class,
            'breadcrumb.item' => Components\Breadcrumb\Item::class,
            'breadcrumb.link' => Components\Breadcrumb\Link::class,
            'breadcrumb.page' => Components\Breadcrumb\Page::class,
            'breadcrumb.separator' => Components\Breadcrumb\Separator::class,
            'breadcrumb.ellipsis' => Components\Breadcrumb\Ellipsis::class,
            'card.action' => Components\Card\Action::class,
            'card.content' => Components\Card\Content::class,
            'card.description' => Components\Card\Description::class,
            'card.footer' => Components\Card\Footer::class,
            'card.header' => Components\Card\Header::class,
            'card.title' => Components\Card\Title::class,
            'checkbox-group.item' => Components\CheckboxGroup\Item::class,
            'radio-group.item' => Components\RadioGroup\Item::class,
            'drawer.trigger' => Components\Drawer\Trigger::class,
            'drawer.content' => Components\Drawer\Content::class,
            'drawer.header' => Components\Drawer\Header::class,
            'drawer.title' => Components\Drawer\Title::class,
            'drawer.description' => Components\Drawer\Description::class,
            'drawer.footer' => Components\Drawer\Footer::class,
            'drawer.close' => Components\Drawer\Close::class,
            'dropdown.item' => Components\Dropdown\Item::class,
            'dropdown.label' => Components\Dropdown\Label::class,
            'dropdown.separator' => Components\Dropdown\Separator::class,
            'dropdown.shortcut' => Components\Dropdown\Shortcut::class,
            'dropdown.group' => Components\Dropdown\Group::class,
            'sheet.trigger' => Components\Sheet\Trigger::class,
            'sheet.content' => Components\Sheet\Content::class,
            'sheet.header' => Components\Sheet\Header::class,
            'sheet.title' => Components\Sheet\Title::class,
            'sheet.description' => Components\Sheet\Description::class,
            'sheet.footer' => Components\Sheet\Footer::class,
            'sheet.close' => Components\Sheet\Close::class,
            'empty-state.content' => Components\EmptyState\Content::class,
            'empty-state.description' => Components\EmptyState\Description::class,
            'empty-state.header' => Components\EmptyState\Header::class,
            'empty-state.media' => Components\EmptyState\Media::class,
            'empty-state.title' => Components\EmptyState\Title::class,
            'field.content' => Components\Field\Content::class,
            'field.description' => Components\Field\Description::class,
            'field.label' => Components\Field\Label::class,
            'field.legend' => Components\Field\Legend::class,
            'field.separator' => Components\Field\Separator::class,
            'field.set' => Components\Field\Set::class,
            'field.title' => Components\Field\Title::class,
            'hover-card.trigger' => Components\HoverCard\Trigger::class,
            'hover-card.content' => Components\HoverCard\Content::class,
            'table.header' => Components\Table\Header::class,
            'table.body' => Components\Table\Body::class,
            'table.footer' => Components\Table\Footer::class,
            'table.row' => Components\Table\Row::class,
            'table.head' => Components\Table\Head::class,
            'table.cell' => Components\Table\Cell::class,
            'table.caption' => Components\Table\Caption::class,
            'tabs.list' => Components\Tabs\TabList::class,
            'tabs.trigger' => Components\Tabs\Trigger::class,
            'tabs.panel' => Components\Tabs\Panel::class,
            'toggle-group.item' => Components\ToggleGroup\Item::class,
            'sidebar.provider' => Components\Sidebar\Provider::class,
            'sidebar.trigger' => Components\Sidebar\Trigger::class,
            'sidebar.rail' => Components\Sidebar\Rail::class,
            'sidebar.inset' => Components\Sidebar\Inset::class,
            'sidebar.header' => Components\Sidebar\Header::class,
            'sidebar.brand' => Components\Sidebar\Brand::class,
            'sidebar.footer' => Components\Sidebar\Footer::class,
            'sidebar.content' => Components\Sidebar\Content::class,
            'sidebar.input' => Components\Sidebar\Input::class,
            'sidebar.separator' => Components\Sidebar\Separator::class,
            'sidebar.group' => Components\Sidebar\Group::class,
            'sidebar.group-label' => Components\Sidebar\GroupLabel::class,
            'sidebar.group-action' => Components\Sidebar\GroupAction::class,
            'sidebar.group-content' => Components\Sidebar\GroupContent::class,
            'sidebar.menu' => Components\Sidebar\Menu::class,
            'sidebar.menu-item' => Components\Sidebar\MenuItem::class,
            'sidebar.menu-button' => Components\Sidebar\MenuButton::class,
            'sidebar.menu-action' => Components\Sidebar\MenuAction::class,
            'sidebar.menu-badge' => Components\Sidebar\MenuBadge::class,
            'sidebar.menu-skeleton' => Components\Sidebar\MenuSkeleton::class,
            'sidebar.menu-sub' => Components\Sidebar\MenuSub::class,
            'sidebar.menu-sub-item' => Components\Sidebar\MenuSubItem::class,
            'sidebar.menu-sub-button' => Components\Sidebar\MenuSubButton::class,
            'item.actions' => Components\Item\Actions::class,
            'item.content' => Components\Item\Content::class,
            'item.description' => Components\Item\Description::class,
            'item.footer' => Components\Item\Footer::class,
            'item.group' => Components\Item\Group::class,
            'item.header' => Components\Item\Header::class,
            'item.media' => Components\Item\Media::class,
            'item.separator' => Components\Item\Separator::class,
            'item.title' => Components\Item\Title::class,
            'kbd.group' => Components\Kbd\Group::class,
            'marker.icon' => Components\Marker\Icon::class,
            'marker.content' => Components\Marker\Content::class,
            'pagination.content' => Components\Pagination\Content::class,
            'pagination.item' => Components\Pagination\Item::class,
            'pagination.link' => Components\Pagination\Link::class,
            'pagination.previous' => Components\Pagination\Previous::class,
            'pagination.next' => Components\Pagination\Next::class,
            'pagination.ellipsis' => Components\Pagination\Ellipsis::class,
            'popover.trigger' => Components\Popover\Trigger::class,
            'popover.content' => Components\Popover\Content::class,
            'popover.header' => Components\Popover\Header::class,
            'popover.title' => Components\Popover\Title::class,
            'popover.description' => Components\Popover\Description::class,
            'progress.track' => Components\Progress\Track::class,
            'progress.indicator' => Components\Progress\Indicator::class,
            'progress.label' => Components\Progress\Label::class,
            'progress.value' => Components\Progress\Value::class,
        ];
    }
}
