<?php

namespace Emaia\LaravelHotwire\Support;

use JsonException;

/** @internal */
final class GeneratedStyleBundle
{
    private const string PLAN_PREFIX = '/* hotwire-preset-bundle-plan: ';

    private const string HASH_PLACEHOLDER = '0000000000000000000000000000000000000000000000000000000000000000';

    /**
     * Render the canonical bundle represented by a generation plan.
     *
     * @param  string[]  $components
     * @param  string[]  $modules
     *
     * @throws JsonException
     */
    public function render(
        string $output,
        PresetSource $source,
        string $preset,
        array $components,
        array $modules,
    ): string {
        $content = $this->renderContent(
            $output,
            $source,
            $this->planComment($preset, $components, $modules, self::HASH_PLACEHOLDER),
        );
        $hash = hash('sha256', $this->normalizeLineEndings($content));

        return preg_replace_callback(
            '/("hash":")'.self::HASH_PLACEHOLDER.'(")/',
            fn (array $match): string => $match[1].$hash.$match[2],
            $content,
            1,
        ) ?? $content;
    }

    /**
     * Render the canonical artifact represented by a readable v1 or v2 plan.
     *
     * @param  array{version: 1, preset: string, components: string[], controllers: string[], modules: string[]}|array{version: 2, preset: string, components: string[], modules: string[], hash: string}  $plan
     * @param  string[]  $modules
     */
    public function renderFromPlan(string $output, PresetSource $source, array $plan, array $modules): string
    {
        if ($plan['version'] === 2) {
            return $this->render($output, $source, $plan['preset'], $plan['components'], $modules);
        }

        return $this->renderContent(
            $output,
            $source,
            $this->legacyPlanComment(
                $plan['preset'],
                $plan['components'],
                $plan['controllers'],
                $modules,
            ),
        );
    }

    private function renderContent(string $output, PresetSource $source, string $planComment): string
    {
        $directory = dirname($output);
        $depth = $directory === '.' ? 0 : count(explode('/', $directory));
        $vendor = ($depth === 0 ? './' : str_repeat('../', $depth))
            .'vendor/emaia/laravel-hotwire/resources/css/';
        $imports = array_map(
            fn (string $path): string => "@import \"{$vendor}{$path}\";",
            $source->foundationImports(),
        );

        return implode("\n", [
            '/* '.PackageMarker::TAG.' */',
            $planComment,
            '/* Generated by `php artisan hotwire:bundle-preset`. Regenerate instead of editing. */',
            '',
            ...$imports,
            '',
            $source->visualCss(),
            '',
        ]);
    }

    /**
     * Render canonical metadata needed to audit and regenerate a selective bundle.
     *
     * @param  string[]  $components
     * @param  string[]  $modules
     *
     * @throws JsonException
     */
    public function planComment(string $preset, array $components, array $modules, string $hash): string
    {
        sort($components);
        sort($modules);

        $plan = json_encode([
            'version' => 2,
            'preset' => $preset,
            'components' => array_values(array_unique($components)),
            'modules' => array_values(array_unique($modules)),
            'hash' => $hash,
        ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);

        return self::PLAN_PREFIX.$plan.' */';
    }

    /**
     * Read a generated bundle plan, returning null for user-owned or malformed CSS.
     *
     * @return array{version: 1, preset: string, components: string[], controllers: string[], modules: string[]}|array{version: 2, preset: string, components: string[], modules: string[], hash: string}|null
     */
    public function planFromContent(string $content): ?array
    {
        $content = $this->normalizeLineEndings($content);

        if (! $this->hasPackageMarker($content)
            || preg_match('/^\/\* hotwire-preset-bundle-plan: (\{.*\}) \*\/$/m', $content, $match) !== 1) {
            return null;
        }

        try {
            $plan = json_decode($match[1], true, flags: JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            return null;
        }

        if (! is_array($plan) || ! is_string($plan['preset'] ?? null)) {
            return null;
        }

        $version = $plan['version'] ?? null;
        $listKeys = $version === 1 ? ['components', 'controllers', 'modules'] : ['components', 'modules'];
        $expectedKeys = $version === 1
            ? ['version', 'preset', 'components', 'controllers', 'modules']
            : ['version', 'preset', 'components', 'modules', 'hash'];

        if (! in_array($version, [1, 2], true) || array_keys($plan) !== $expectedKeys) {
            return null;
        }

        foreach ($listKeys as $key) {
            if (! is_array($plan[$key] ?? null)
                || ! array_is_list($plan[$key])
                || array_filter($plan[$key], fn (mixed $value): bool => ! is_string($value)) !== []) {
                return null;
            }
        }

        if ($version === 2 && (! is_string($plan['hash'] ?? null) || preg_match('/^[a-f0-9]{64}$/', $plan['hash']) !== 1)) {
            return null;
        }

        /** @var array{version: 1, preset: string, components: string[], controllers: string[], modules: string[]}|array{version: 2, preset: string, components: string[], modules: string[], hash: string} $plan */
        return $plan;
    }

    /** Verify that a v2 artifact still matches the hash recorded at generation time. */
    public function hashMatches(string $content): bool
    {
        $plan = $this->planFromContent($content);

        if ($plan === null || $plan['version'] !== 2) {
            return false;
        }

        $normalized = $this->normalizeLineEndings($content);
        $placeholder = preg_replace_callback(
            '/("hash"\s*:\s*")'.preg_quote($plan['hash'], '/').'(")/',
            fn (array $match): string => $match[1].self::HASH_PLACEHOLDER.$match[2],
            $normalized,
            1,
            $replacements,
        );

        return $replacements === 1
            && is_string($placeholder)
            && hash_equals($plan['hash'], hash('sha256', $placeholder));
    }

    /** Identify package-owned output from this command even when its metadata is stale. */
    public function looksGenerated(string $content): bool
    {
        return $this->planFromContent($content) !== null
            || $this->hasPackageMarker($content)
            && str_contains($content, 'Generated by `php artisan hotwire:bundle-preset`.');
    }

    /** Compare generated CSS without treating checkout line endings as content drift. */
    public function matches(string $content, string $expected): bool
    {
        return $this->normalizeLineEndings($content) === $this->normalizeLineEndings($expected);
    }

    /**
     * @param  string[]  $components
     * @param  string[]  $controllers
     * @param  string[]  $modules
     *
     * @throws JsonException
     */
    private function legacyPlanComment(string $preset, array $components, array $controllers, array $modules): string
    {
        sort($components);
        sort($controllers);
        sort($modules);

        $plan = json_encode([
            'version' => 1,
            'preset' => $preset,
            'components' => array_values(array_unique($components)),
            'controllers' => array_values(array_unique($controllers)),
            'modules' => array_values(array_unique($modules)),
        ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);

        return self::PLAN_PREFIX.$plan.' */';
    }

    private function normalizeLineEndings(string $content): string
    {
        return str_replace(["\r\n", "\r"], "\n", $content);
    }

    private function hasPackageMarker(string $content): bool
    {
        foreach (preg_split('/\R/', $content) ?: [] as $line) {
            if (trim($line) === '') {
                continue;
            }

            return str_contains($line, PackageMarker::TAG);
        }

        return false;
    }
}
