<?php

namespace Emaia\LaravelHotwire\Support;

use JsonException;

/** @internal */
final class GeneratedStyleBundle
{
    private const string PLAN_PREFIX = '/* hotwire-styles-plan: ';

    /**
     * Render canonical metadata needed to audit and regenerate a selective bundle.
     *
     * @param  string[]  $components
     * @param  string[]  $controllers
     * @param  string[]  $modules
     *
     * @throws JsonException
     */
    public function planComment(string $preset, array $components, array $controllers, array $modules): string
    {
        sort($components);
        sort($controllers);
        sort($modules);

        $plan = json_encode([
            'version' => 1,
            'preset' => $preset,
            'components' => array_values(array_unique($components)),
            'controllers' => array_values(array_unique($controllers)),
            'modules' => array_values(array_unique($modules)),
        ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);

        return self::PLAN_PREFIX.$plan.' */';
    }

    /**
     * Read a generated bundle plan, returning null for user-owned or malformed CSS.
     *
     * @return array{version: 1, preset: string, components: string[], controllers: string[], modules: string[]}|null
     */
    public function planFromContent(string $content): ?array
    {
        if (! $this->hasPackageMarker($content)
            || preg_match('/^\/\* hotwire-styles-plan: (\{.*\}) \*\/$/m', $content, $match) !== 1) {
            return null;
        }

        try {
            $plan = json_decode($match[1], true, flags: JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            return null;
        }

        if (! is_array($plan) || ($plan['version'] ?? null) !== 1 || ! is_string($plan['preset'] ?? null)) {
            return null;
        }

        foreach (['components', 'controllers', 'modules'] as $key) {
            if (! is_array($plan[$key] ?? null) || array_filter($plan[$key], fn (mixed $value): bool => ! is_string($value)) !== []) {
                return null;
            }
        }

        /** @var array{version: 1, preset: string, components: string[], controllers: string[], modules: string[]} $plan */
        return $plan;
    }

    /** Identify package-owned output from this command even when its metadata is stale. */
    public function looksGenerated(string $content): bool
    {
        return $this->hasPackageMarker($content)
            && str_contains($content, 'Generated by `php artisan hotwire:styles`.');
    }

    private function hasPackageMarker(string $content): bool
    {
        foreach (preg_split('/\R/', $content) ?: [] as $line) {
            if (trim($line) === '') {
                continue;
            }

            return str_contains($line, PackageMarker::TAG);
        }

        return false;
    }
}
