<?php

namespace Emaia\LaravelHotwire\Support;

use Emaia\LaravelHotwire\Registry\HotwireRegistry;

/**
 * Generates the contents of `resources/js/controllers/index.js` from the
 * catalog + an install opt-in selection. The user's stub is no longer a
 * bit-for-bit copy of the package stub; `hotwire:install` and
 * `hotwire:check --fix` produce it via this helper.
 *
 * The first line is a fixed marker comment so other commands can detect
 * (and safely regenerate) an auto-generated file vs one a user has hand-edited.
 */
final class LoaderStub
{
    public const string MARKER = '// AUTO-GENERATED by hotwire:install — DO NOT EDIT MANUALLY.';

    private const string PACKAGE_GLOB = '../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js';

    /**
     * Build the loader stub.
     *
     * $optIn modes:
     *   - null:  default — every package controller globbed (no exclusions).
     *   - []:    core-only — every com-dep package controller excluded.
     *   - list:  subset — only the listed com-dep controllers + every zero-dep controller globbed.
     *
     * @param  string[]|null  $optIn
     */
    public static function generate(HotwireRegistry $registry, ?array $optIn = null): string
    {
        $marker = self::MARKER;
        $exclusions = self::exclusions($registry, $optIn);
        $globArgument = self::globArgument($exclusions);

        return <<<JS
            {$marker}
            // Re-run `php artisan hotwire:install` (or `hotwire:check --fix`) to regenerate.
            import { Stimulus } from "../libs/stimulus";
            import { registerControllers } from "@emaia/stimulus-dynamic-loader";

            const userControllers = import.meta.glob(
                "./**/*_controller.{js,ts}",
                { eager: false }
            );

            const packageControllers = import.meta.glob(
                {$globArgument},
                { eager: false }
            );

            registerControllers(Stimulus, { ...packageControllers, ...userControllers }, { warnOnDuplicate: false });

            JS;
    }

    /** Detect whether a given file content was produced by `generate`. */
    public static function isAutoGenerated(string $content): bool
    {
        return str_starts_with(ltrim($content), self::MARKER);
    }

    /**
     * Identifiers of com-dep package controllers currently included in the
     * generated stub. Returns null when the content is not auto-generated.
     *
     * @return string[]|null
     */
    public static function includedComDepControllers(string $content, HotwireRegistry $registry): ?array
    {
        if (! self::isAutoGenerated($content)) {
            return null;
        }

        preg_match_all('/!\*\*\/([a-z0-9_-]+_controller\.js)/i', $content, $matches);
        $excludedFilenames = $matches[1] ?? [];

        $included = [];

        foreach ($registry->controllers() as $identifier => $controller) {
            if (empty($controller->npm)) {
                continue;
            }

            if (! in_array($controller->filename(), $excludedFilenames, true)) {
                $included[] = $identifier;
            }
        }

        return $included;
    }

    /** @return string[] */
    private static function exclusions(HotwireRegistry $registry, ?array $optIn): array
    {
        if ($optIn === null) {
            return [];
        }

        $exclusions = [];

        foreach ($registry->controllers() as $identifier => $controller) {
            if (empty($controller->npm)) {
                continue;
            }

            if (in_array($identifier, $optIn, true)) {
                continue;
            }

            $exclusions[] = $controller->filename();
        }

        sort($exclusions);

        return $exclusions;
    }

    /** @param  string[]  $exclusions */
    private static function globArgument(array $exclusions): string
    {
        if ($exclusions === []) {
            return '"'.self::PACKAGE_GLOB.'"';
        }

        $lines = ['        "'.self::PACKAGE_GLOB.'",'];

        foreach ($exclusions as $filename) {
            $lines[] = '        "!**/'.$filename.'",';
        }

        return "[\n".implode("\n", $lines)."\n    ]";
    }
}
