<?php

namespace Emaia\LaravelHotwire\Support;

use Emaia\LaravelHotwire\Registry\HotwireRegistry;
use Illuminate\Filesystem\Filesystem;

final class LoaderStub
{
    public const string MARKER = '// AUTO-GENERATED by hotwire:install — DO NOT EDIT MANUALLY.';

    private const string METADATA_PREFIX = '// hotwire-loader-plan: ';

    private const string PACKAGE_GLOB = '../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js';

    private const string APPLICATION_GLOB = './**/*_controller.{js,ts}';

    /**
     * Build the loader stub while preserving the existing dependency opt-in modes.
     *
     * @param  string[]|null  $optIn  Null includes all dependency-bearing package controllers.
     * @param  string[]  $preloadControllers
     * @param  string[]  $eagerControllers
     */
    public static function generate(
        HotwireRegistry $registry,
        ?array $optIn = null,
        array $preloadControllers = [],
        array $eagerControllers = [],
        ?string $appControllersPath = null,
    ): string {
        $appControllersPath ??= function_exists('resource_path')
            ? resource_path('js/controllers')
            : getcwd().'/resources/js/controllers';

        return self::generateFromPlan(ControllerLoadPlan::make(
            new Filesystem,
            $registry,
            $appControllersPath,
            $optIn,
            $preloadControllers,
            $eagerControllers,
        ));
    }

    /** Generate a lazy-loader v2 registry from an inspectable controller load plan. */
    public static function generateFromPlan(ControllerLoadPlan $plan): string
    {
        $metadata = json_encode(
            $plan->policy->toArray(),
            JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR,
        );
        $packageExclusions = array_merge(
            array_map(
                fn (string $path) => '!**/'.basename($path),
                $plan->excludedPackagePaths,
            ),
            array_map(
                fn (ResolvedController $controller) => '!'.$controller->loaderPath,
                $plan->eagerPackageControllers,
            ),
        );
        $applicationExclusions = array_map(
            fn (ResolvedController $controller) => '!'.$controller->loaderPath,
            $plan->eagerApplicationControllers,
        );

        $registries = [];
        $blocks = [self::globBlock('packageControllers', self::PACKAGE_GLOB, $packageExclusions)];

        if ($plan->eagerPackageControllers !== []) {
            $blocks[] = self::globBlock(
                'eagerPackageControllers',
                array_map(fn (ResolvedController $controller) => $controller->loaderPath, $plan->eagerPackageControllers),
                eager: true,
            );
        }

        $blocks[] = self::globBlock('userControllers', self::APPLICATION_GLOB, $applicationExclusions);

        if ($plan->eagerApplicationControllers !== []) {
            $blocks[] = self::globBlock(
                'eagerUserControllers',
                array_map(fn (ResolvedController $controller) => $controller->loaderPath, $plan->eagerApplicationControllers),
                eager: true,
            );
        }

        $registries[] = '    ...packageControllers,';

        if ($plan->eagerPackageControllers !== []) {
            $registries[] = '    ...eagerPackageControllers,';
        }

        $registries[] = '    ...userControllers,';

        if ($plan->eagerApplicationControllers !== []) {
            $registries[] = '    ...eagerUserControllers,';
        }

        $blocks = implode("\n\n", $blocks);
        $registries = implode("\n", $registries);
        $marker = self::MARKER;
        $metadataLine = self::METADATA_PREFIX.$metadata;

        return <<<JS
            {$marker}
            {$metadataLine}
            // Re-run `php artisan hotwire:install` (or `hotwire:check --fix`) to regenerate.
            import { Stimulus } from "../hotwire/stimulus";
            import { registerControllers } from "@emaia/stimulus-lazy-loader";

            {$blocks}

            registerControllers(Stimulus, {
            {$registries}
            }, { warnOnDuplicate: false });

            JS;
    }

    /** Detect whether a given file content was produced by `generate`. */
    public static function isAutoGenerated(string $content): bool
    {
        return str_starts_with(ltrim($content), self::MARKER);
    }

    /**
     * Read supported regeneration metadata without inferring policy from JavaScript.
     */
    public static function policyFromContent(string $content): ?ControllerLoadPolicy
    {
        if (! self::isAutoGenerated($content)) {
            return null;
        }

        if (! preg_match('/^'.preg_quote(self::METADATA_PREFIX, '/').'(.+)$/m', $content, $match)) {
            return null;
        }

        $metadata = json_decode($match[1], true);

        if (! is_array($metadata)
            || ! in_array($metadata['version'] ?? null, [2, 3], true)
            || ! is_bool($metadata['includeAllComDepControllers'] ?? null)
        ) {
            return null;
        }

        foreach (['includedComDepControllers', 'preloadControllers', 'eagerControllers'] as $key) {
            $identifiers = $metadata[$key] ?? null;

            if (! is_array($identifiers) || ! array_is_list($identifiers)
                || array_filter($identifiers, 'is_string') !== $identifiers
            ) {
                return null;
            }
        }

        // Schema 2 records the selection explicitly, but predates eager path tracking.
        $paths = $metadata['version'] === 3 ? ($metadata['eagerControllerPaths'] ?? null) : [];

        if (! is_array($paths) || array_filter(
            $paths,
            fn (mixed $path, mixed $identifier): bool => is_string($identifier) && is_string($path),
            ARRAY_FILTER_USE_BOTH,
        ) !== $paths) {
            return null;
        }

        return new ControllerLoadPolicy(
            $metadata['includedComDepControllers'],
            $metadata['preloadControllers'],
            $metadata['eagerControllers'],
            includeAllComDepControllers: $metadata['includeAllComDepControllers'],
            eagerControllerPaths: $paths,
        );
    }

    /**
     * Report dependency-bearing package controllers included by an auto-generated stub.
     *
     * @return string[]|null
     */
    public static function includedComDepControllers(string $content): ?array
    {
        return self::policyFromContent($content)?->includedComDepControllers;
    }

    /** @param  string|string[]  $patterns */
    private static function globBlock(string $name, string|array $patterns, array $exclusions = [], bool $eager = false): string
    {
        $patterns = array_values(array_merge(is_array($patterns) ? $patterns : [$patterns], $exclusions));
        $argument = count($patterns) === 1
            ? json_encode($patterns[0], JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)
            : self::javascriptArray($patterns, 4);
        $eagerValue = $eager ? 'true' : 'false';

        return <<<JS
            const {$name} = import.meta.glob(
                {$argument},
                { eager: {$eagerValue} }
            );
            JS;
    }

    /** @param  string[]  $values */
    private static function javascriptArray(array $values, int $indent): string
    {
        $padding = str_repeat(' ', $indent);
        $items = array_map(
            fn (string $value) => $padding.'    '.json_encode($value, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).',',
            $values,
        );

        return "[\n".implode("\n", $items)."\n{$padding}]";
    }
}
