<?php

namespace Emaia\LaravelHotwire\Commands;

use Emaia\LaravelHotwire\Registry\HotwireRegistry;
use Emaia\LaravelHotwire\Support\CssModuleManifest;
use Emaia\LaravelHotwire\Support\CssPresetFiles;
use Emaia\LaravelHotwire\Support\GeneratedStyleBundle;
use Emaia\LaravelHotwire\Support\PresetSourceException;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function Laravel\Prompts\info;
use function Laravel\Prompts\warning;

class StylesCommand extends Command
{
    public $signature = 'hotwire:styles
                        {--preset=nova : Shipped preset to use}
                        {--components=* : Component keys to include (comma-separated or repeated)}
                        {--include=* : Additional component or controller keys}
                        {--output=resources/css/hotwire.css : Output path under resources/css}
                        {--force : Replace an existing generated bundle}';

    public $description = 'Generate a selective Hotwire CSS bundle';

    public function __construct(
        private readonly Filesystem $files,
        private readonly CssPresetFiles $presets,
        private readonly CssModuleManifest $manifest,
        private readonly GeneratedStyleBundle $bundle,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $preset = (string) $this->option('preset');

        if (! in_array($preset, $this->presets->names(), true)) {
            warning("Unknown preset \"{$preset}\". Use one of: ".implode(', ', $this->presets->names()).'.');

            return self::FAILURE;
        }

        $selection = $this->selection();

        if ($selection === null) {
            return self::FAILURE;
        }

        [$components, $controllers] = $selection;

        if ($components === [] && $controllers === []) {
            warning('Select at least one component or controller.');

            return self::FAILURE;
        }

        $output = $this->outputPath();

        if ($output === null) {
            return self::FAILURE;
        }

        $target = $this->outputTarget($output);

        if ($target === null) {
            return self::FAILURE;
        }

        try {
            $source = $this->presets->sourceForSelection($preset, $components, $controllers);
        } catch (PresetSourceException $exception) {
            warning($exception->getMessage());

            return self::FAILURE;
        }

        if ($source === null) {
            warning("Unknown preset \"{$preset}\".");

            return self::FAILURE;
        }

        $modules = $this->manifest->modulesFor($components, $controllers);
        $content = $this->bundle->render(
            $output,
            $source,
            $preset,
            $components,
            $controllers,
            $modules,
        );

        if ($this->files->exists($target)) {
            $existing = $this->files->get($target);

            if ($this->bundle->matches($existing, $content)) {
                info("Up to date: {$output}");

                return self::SUCCESS;
            }

            if (! $this->bundle->looksGenerated($existing)) {
                warning("Output [{$output}] was not generated by Laravel Hotwire and will not be overwritten.");

                return self::FAILURE;
            }

            if (! $this->option('force')) {
                warning("Output already exists: {$output}. Use --force to overwrite.");

                return self::FAILURE;
            }
        }

        $this->files->ensureDirectoryExists(dirname($target));
        $this->files->put($target, $content);

        info("Generated: {$output}");

        return self::SUCCESS;
    }

    /**
     * @return array{string[], string[]}|null
     */
    private function selection(): ?array
    {
        $registry = HotwireRegistry::make();
        $components = [];
        $controllers = [];

        foreach ($this->optionValues('components') as $key) {
            $component = $registry->component($key);

            if ($component === null) {
                warning("Unknown component \"{$key}\".");

                return null;
            }

            $components[] = $key;

            foreach ($registry->controllersForComponent($component) as $controller) {
                $controllers[] = $controller->identifier;
            }
        }

        foreach ($this->optionValues('include') as $key) {
            $component = $registry->component($key);

            if ($component !== null) {
                $components[] = $key;

                foreach ($registry->controllersForComponent($component) as $controller) {
                    $controllers[] = $controller->identifier;
                }

                continue;
            }

            $identifier = str_replace('/', '--', $key);
            $controller = $registry->controller($identifier);

            if ($controller === null) {
                warning("Unknown component or controller \"{$key}\".");

                return null;
            }

            $controllers[] = $controller->identifier;
        }

        return [
            array_values(array_unique($components)),
            array_values(array_unique($controllers)),
        ];
    }

    /** @return string[] */
    private function optionValues(string $name): array
    {
        $values = $this->option($name);
        $values = is_array($values) ? $values : [$values];

        return array_values(array_unique(array_filter(array_map(
            trim(...),
            array_merge(...array_map(fn (mixed $value): array => explode(',', (string) $value), $values)),
        ))));
    }

    private function outputPath(): ?string
    {
        $output = str_replace('\\', '/', trim((string) $this->option('output')));
        $segments = explode('/', $output);

        if ($output === '' || str_starts_with($output, '/') || preg_match('/^[A-Za-z]:\//', $output) === 1
            || str_contains($output, ':') || in_array('..', $segments, true)
            || pathinfo($output, PATHINFO_EXTENSION) !== 'css') {
            warning('Output must be a relative .css path under resources/css.');

            return null;
        }

        $output = implode('/', array_values(array_filter($segments, fn (string $segment): bool => $segment !== '' && $segment !== '.')));
        $segments = explode('/', $output);

        if (! str_starts_with($output, 'resources/css/')
            || array_filter($segments, fn (string $segment): bool => str_starts_with($segment, '.')) !== []) {
            warning('Output must be a relative .css path under resources/css.');

            return null;
        }

        return $output;
    }

    private function outputTarget(string $output): ?string
    {
        $target = base_path($output);
        $application = realpath(base_path());
        $styles = resource_path('css');
        $existing = $styles;

        while (! file_exists($existing) && ! is_link($existing)) {
            $parent = dirname($existing);

            if ($parent === $existing) {
                break;
            }

            $existing = $parent;
        }

        $resolvedParent = realpath($existing);

        if ($application === false || is_link($existing) || $resolvedParent === false
            || ! $this->containsPath($application, $resolvedParent)) {
            warning('Output must resolve inside resources/css.');

            return null;
        }

        $this->files->ensureDirectoryExists($styles);

        if ($this->traversesSymlink($styles, $target)) {
            warning('Output must resolve inside resources/css.');

            return null;
        }

        $styles = realpath($styles);
        $existing = $target;

        while (! file_exists($existing) && ! is_link($existing)) {
            $parent = dirname($existing);

            if ($parent === $existing) {
                break;
            }

            $existing = $parent;
        }

        $resolved = realpath($existing);

        if ($styles === false || is_link($existing) || $resolved === false
            || ! $this->containsPath($application, $styles) || ! $this->containsPath($styles, $resolved)) {
            warning('Output must resolve inside resources/css.');

            return null;
        }

        return $target;
    }

    private function containsPath(string $parent, string $path): bool
    {
        $parent = str_replace('\\', '/', $parent);
        $path = str_replace('\\', '/', $path);

        if (PHP_OS_FAMILY === 'Windows') {
            $parent = strtolower($parent);
            $path = strtolower($path);
        }

        return $path === $parent || str_starts_with($path, rtrim($parent, '/').'/');
    }

    private function traversesSymlink(string $root, string $target): bool
    {
        $root = rtrim(str_replace('\\', '/', $root), '/');
        $target = str_replace('\\', '/', $target);
        $current = $root;

        foreach (explode('/', substr($target, strlen($root) + 1)) as $segment) {
            $current .= '/'.$segment;

            if (is_link($current)) {
                return true;
            }
        }

        return false;
    }
}
