<?php

namespace Emaia\LaravelHotwire\Commands;

use Emaia\LaravelHotwire\Registry\HotwireRegistry;
use Emaia\LaravelHotwire\Support\CssPresetFiles;
use Emaia\LaravelHotwire\Support\PackageMarker;
use Emaia\LaravelHotwire\Support\PresetSource;
use Emaia\LaravelHotwire\Support\PresetSourceException;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function Laravel\Prompts\info;
use function Laravel\Prompts\warning;

class StylesCommand extends Command
{
    public $signature = 'hotwire:styles
                        {--preset=nova : Shipped preset to use}
                        {--components=* : Component keys to include (comma-separated or repeated)}
                        {--include=* : Additional component or controller keys}
                        {--output=resources/css/hotwire.css : Application-relative output path}
                        {--force : Replace an existing generated bundle}';

    public $description = 'Generate a selective Hotwire CSS bundle';

    public function __construct(
        private readonly Filesystem $files,
        private readonly CssPresetFiles $presets,
        private readonly PackageMarker $marker,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $preset = (string) $this->option('preset');

        if (! in_array($preset, $this->presets->names(), true)) {
            warning("Unknown preset \"{$preset}\". Use one of: ".implode(', ', $this->presets->names()).'.');

            return self::FAILURE;
        }

        $selection = $this->selection();

        if ($selection === null) {
            return self::FAILURE;
        }

        [$components, $controllers] = $selection;

        if ($components === [] && $controllers === []) {
            warning('Select at least one component or controller.');

            return self::FAILURE;
        }

        $output = $this->outputPath();

        if ($output === null) {
            return self::FAILURE;
        }

        try {
            $source = $this->presets->sourceForSelection($preset, $components, $controllers);
        } catch (PresetSourceException $exception) {
            warning($exception->getMessage());

            return self::FAILURE;
        }

        if ($source === null) {
            warning("Unknown preset \"{$preset}\".");

            return self::FAILURE;
        }

        $content = $this->content($output, $source);
        $target = base_path($output);

        if ($this->files->exists($target)) {
            if ($this->files->get($target) === $content) {
                info("Up to date: {$output}");

                return self::SUCCESS;
            }

            if (! $this->marker->isPackageOwned($target)) {
                warning("Output [{$output}] was not generated by Laravel Hotwire and will not be overwritten.");

                return self::FAILURE;
            }

            if (! $this->option('force')) {
                warning("Output already exists: {$output}. Use --force to overwrite.");

                return self::FAILURE;
            }
        }

        $this->files->ensureDirectoryExists(dirname($target));
        $this->files->put($target, $content);

        info("Generated: {$output}");

        return self::SUCCESS;
    }

    /**
     * @return array{string[], string[]}|null
     */
    private function selection(): ?array
    {
        $registry = HotwireRegistry::make();
        $components = [];
        $controllers = [];

        foreach ($this->optionValues('components') as $key) {
            $component = $registry->component($key);

            if ($component === null) {
                warning("Unknown component \"{$key}\".");

                return null;
            }

            $components[] = $key;

            foreach ($registry->controllersForComponent($component) as $controller) {
                $controllers[] = $controller->identifier;
            }
        }

        foreach ($this->optionValues('include') as $key) {
            $component = $registry->component($key);

            if ($component !== null) {
                $components[] = $key;

                foreach ($registry->controllersForComponent($component) as $controller) {
                    $controllers[] = $controller->identifier;
                }

                continue;
            }

            $identifier = str_replace('/', '--', $key);
            $controller = $registry->controller($identifier);

            if ($controller === null) {
                warning("Unknown component or controller \"{$key}\".");

                return null;
            }

            $controllers[] = $controller->identifier;
        }

        return [
            array_values(array_unique($components)),
            array_values(array_unique($controllers)),
        ];
    }

    /** @return string[] */
    private function optionValues(string $name): array
    {
        $values = $this->option($name);
        $values = is_array($values) ? $values : [$values];

        return array_values(array_unique(array_filter(array_map(
            trim(...),
            array_merge(...array_map(fn (mixed $value): array => explode(',', (string) $value), $values)),
        ))));
    }

    private function outputPath(): ?string
    {
        $output = str_replace('\\', '/', trim((string) $this->option('output')));
        $segments = explode('/', $output);

        if ($output === '' || str_starts_with($output, '/') || preg_match('/^[A-Za-z]:\//', $output) === 1
            || in_array('..', $segments, true) || pathinfo($output, PATHINFO_EXTENSION) !== 'css') {
            warning('Output must be a relative path inside the application ending in .css.');

            return null;
        }

        return implode('/', array_values(array_filter($segments, fn (string $segment): bool => $segment !== '' && $segment !== '.')));
    }

    private function content(string $output, PresetSource $source): string
    {
        $directory = dirname($output);
        $depth = $directory === '.' ? 0 : count(explode('/', $directory));
        $vendor = ($depth === 0 ? './' : str_repeat('../', $depth))
            .'vendor/emaia/laravel-hotwire/resources/css/';
        $imports = array_map(
            fn (string $path): string => "@import \"{$vendor}{$path}\";",
            $source->foundationImports(),
        );

        return implode("\n", [
            '/* '.PackageMarker::TAG.' */',
            '/* Generated by `php artisan hotwire:styles`. Regenerate instead of editing. */',
            '',
            ...$imports,
            '',
            $source->visualCss(),
            '',
        ]);
    }
}
