// AUTO-GENERATED by hotwire:install — DO NOT EDIT MANUALLY.
// Re-run `php artisan hotwire:install` (or `hotwire:check --fix`) to regenerate.
import { Stimulus } from "../libs/stimulus";
import { registerControllers } from "@emaia/stimulus-lazy-loader";

const userControllers = import.meta.glob(
    "./**/*_controller.{js,ts}",
    { eager: false }
);

const packageControllers = import.meta.glob(
    "../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js",
    { eager: false }
);

registerControllers(Stimulus, { ...packageControllers, ...userControllers }, { warnOnDuplicate: false });
