// AUTO-GENERATED by hotwire:install — DO NOT EDIT MANUALLY.
// hotwire-loader-plan: {"version":3,"includeAllComDepControllers":true,"includedComDepControllers":["carousel","chart","dropdown","hover-card","input-mask","map","multi-select","popover","rich-text","tooltip"],"preloadControllers":[],"eagerControllers":[],"eagerControllerPaths":[]}
// Re-run `php artisan hotwire:install` (or `hotwire:check --fix`) to regenerate.
import { Stimulus } from "../libs/stimulus";
import { registerControllers } from "@emaia/stimulus-lazy-loader";

const packageControllers = import.meta.glob(
    "../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js",
    { eager: false }
);

const userControllers = import.meta.glob(
    "./**/*_controller.{js,ts}",
    { eager: false }
);

registerControllers(Stimulus, {
    ...packageControllers,
    ...userControllers,
}, { warnOnDuplicate: false });
