<?php

$module = static fn (
    array $components = [],
    array $controllers = [],
    array $dependencies = [],
): array => compact('components', 'controllers', 'dependencies');

$novaModules = [
    'accordion',
    'alert',
    'alert-dialog',
    'text-shimmer',
    'attachment',
    'avatar',
    'back-to-top',
    'badge',
    'breadcrumb',
    'button-surfaces',
    'button-group',
    'card',
    'carousel',
    'choice-groups',
    'drawer',
    'floating-presence',
    'dropdown',
    'empty-state',
    'field',
    'file',
    'file-upload',
    'hover-card',
    'icon',
    'control-wrappers',
    'clearable-input-layout',
    'text-controls',
    'checkable-controls',
    'clear-input-button',
    'input-group',
    'item',
    'kbd',
    'marker',
    'modal-overlay-layout',
    'dialog-backdrops',
    'modal',
    'multi-select',
    'sticky',
    'navbar',
    'pagination',
    'popover',
    'progress',
    'read-more',
    'reveal-surfaces',
    'rich-text',
    'scroll-progress',
    'select',
    'separators',
    'sheet',
    'side-panel',
    'sidebar',
    'skeleton',
    'slider',
    'spinner',
    'switch',
    'table',
    'tabs',
    'textarea',
    'timeago',
    'toaster',
    'toggle-controls',
    'toggle-group',
    'tooltip',
    'oembed',
];

return [
    'foundation' => [
        'properties' => [
            '--background',
            '--foreground',
            '--card',
            '--card-foreground',
            '--popover',
            '--popover-foreground',
            '--primary',
            '--primary-foreground',
            '--secondary',
            '--secondary-foreground',
            '--muted',
            '--muted-foreground',
            '--accent',
            '--accent-foreground',
            '--destructive',
            '--destructive-foreground',
            '--border',
            '--backdrop',
            '--input',
            '--ring',
            '--sidebar',
            '--sidebar-foreground',
            '--sidebar-primary',
            '--sidebar-primary-foreground',
            '--sidebar-accent',
            '--sidebar-accent-foreground',
            '--sidebar-border',
            '--sidebar-ring',
            '--radius',
        ],
        'aliases' => [
            '--color-background' => '--background',
            '--color-foreground' => '--foreground',
            '--color-card' => '--card',
            '--color-card-foreground' => '--card-foreground',
            '--color-popover' => '--popover',
            '--color-popover-foreground' => '--popover-foreground',
            '--color-primary' => '--primary',
            '--color-primary-foreground' => '--primary-foreground',
            '--color-secondary' => '--secondary',
            '--color-secondary-foreground' => '--secondary-foreground',
            '--color-muted' => '--muted',
            '--color-muted-foreground' => '--muted-foreground',
            '--color-accent' => '--accent',
            '--color-accent-foreground' => '--accent-foreground',
            '--color-destructive' => '--destructive',
            '--color-destructive-foreground' => '--destructive-foreground',
            '--color-border' => '--border',
            '--color-backdrop' => '--backdrop',
            '--color-input' => '--input',
            '--color-ring' => '--ring',
            '--color-sidebar' => '--sidebar',
            '--color-sidebar-foreground' => '--sidebar-foreground',
            '--color-sidebar-primary' => '--sidebar-primary',
            '--color-sidebar-primary-foreground' => '--sidebar-primary-foreground',
            '--color-sidebar-accent' => '--sidebar-accent',
            '--color-sidebar-accent-foreground' => '--sidebar-accent-foreground',
            '--color-sidebar-border' => '--sidebar-border',
            '--color-sidebar-ring' => '--sidebar-ring',
            '--radius-sm' => '--radius',
            '--radius-md' => '--radius',
            '--radius-lg' => '--radius',
            '--radius-xl' => '--radius',
            '--radius-2xl' => '--radius',
            '--radius-3xl' => '--radius',
            '--radius-4xl' => '--radius',
        ],
        'contrast_pairs' => [
            'background' => ['foreground' => '--foreground', 'background' => '--background'],
            'card' => ['foreground' => '--card-foreground', 'background' => '--card'],
            'popover' => ['foreground' => '--popover-foreground', 'background' => '--popover'],
            'primary' => ['foreground' => '--primary-foreground', 'background' => '--primary'],
            'secondary' => ['foreground' => '--secondary-foreground', 'background' => '--secondary'],
            'muted' => ['foreground' => '--muted-foreground', 'background' => '--muted'],
            'accent' => ['foreground' => '--accent-foreground', 'background' => '--accent'],
            'destructive' => ['foreground' => '--destructive-foreground', 'background' => '--destructive'],
            'sidebar' => ['foreground' => '--sidebar-foreground', 'background' => '--sidebar'],
            'sidebar-primary' => ['foreground' => '--sidebar-primary-foreground', 'background' => '--sidebar-primary'],
            'sidebar-accent' => ['foreground' => '--sidebar-accent-foreground', 'background' => '--sidebar-accent'],
        ],
    ],
    'modules' => [
        'accordion' => $module(['accordion']),
        'alert' => $module(['alert']),
        'alert-dialog' => $module(['alert-dialog']),
        'text-shimmer' => $module(['attachment', 'skeleton']),
        'attachment' => $module(['attachment'], dependencies: ['button-surfaces']),
        'avatar' => $module(['avatar']),
        'back-to-top' => $module(['back-to-top']),
        'badge' => $module(['badge']),
        'breadcrumb' => $module(['breadcrumb']),
        'button-surfaces' => $module([
            'button',
            'attachment',
            'modal',
            'alert-dialog',
            'hover-card',
            'color-scheme.toggle',
            'back-to-top',
            'read-more',
        ]),
        'button-group' => $module(['button-group']),
        'card' => $module(['card']),
        'carousel' => $module(['carousel']),
        'choice-groups' => $module([
            'checkbox-group',
            'checkbox-group.item',
            'radio-group',
            'radio-group.item',
        ]),
        'drawer' => $module(['drawer']),
        'floating-presence' => $module(
            ['dropdown', 'hover-card', 'popover', 'multi-select', 'tooltip'],
        ),
        'dropdown' => $module(['dropdown']),
        'empty-state' => $module(['empty-state']),
        'field' => $module(['field', 'field.error', 'field.group', 'field.label']),
        'file' => $module(['file']),
        'file-upload' => $module(
            ['file-upload'],
            dependencies: ['attachment', 'empty-state', 'icon', 'progress', 'text-shimmer'],
        ),
        'hover-card' => $module(['hover-card']),
        'icon' => $module(['icon']),
        'control-wrappers' => $module(['input', 'textarea', 'file']),
        'clearable-input-layout' => $module(['input', 'multi-select']),
        'text-controls' => $module(['input', 'select']),
        'checkable-controls' => $module([
            'input',
            'checkbox',
            'checkbox-group',
            'checkbox-group.item',
            'radio-group',
            'radio-group.item',
        ]),
        'clear-input-button' => $module(['input', 'multi-select']),
        'input-group' => $module(['input-group']),
        'item' => $module(['item']),
        'kbd' => $module(['kbd']),
        'marker' => $module(['marker']),
        'modal-overlay-layout' => $module(['modal']),
        'dialog-backdrops' => $module(['modal', 'alert-dialog']),
        'modal' => $module(['modal']),
        'multi-select' => $module(['multi-select'], dependencies: ['input-group']),
        'sticky' => $module(['sticky', 'navbar']),
        'navbar' => $module(['navbar', 'navbar.item']),
        'pagination' => $module(['pagination']),
        'popover' => $module(['popover']),
        'progress' => $module(['progress']),
        'read-more' => $module(['read-more']),
        'reveal-surfaces' => $module(['reveal', 'reveal.item', 'sidebar']),
        'rich-text' => $module(['rich-text']),
        'scroll-progress' => $module(['scroll-progress']),
        'select' => $module(['select']),
        'separators' => $module(['separator', 'item', 'button-group']),
        'sheet' => $module(['sheet']),
        'side-panel' => $module(['side-panel']),
        'sidebar' => $module(['sidebar']),
        'skeleton' => $module(['skeleton']),
        'slider' => $module(['slider']),
        'spinner' => $module(['spinner']),
        'switch' => $module(['switch']),
        'table' => $module(['table']),
        'tabs' => $module(['tabs']),
        'textarea' => $module(['textarea']),
        'timeago' => $module(['timeago']),
        'toggle-controls' => $module(['toggle', 'toggle-group', 'toggle-group.item']),
        'toggle-group' => $module(['toggle-group', 'toggle-group.item']),
        'tooltip' => $module(['button', 'color-scheme.toggle', 'sidebar', 'tooltip'], dependencies: ['floating-presence', 'kbd']),
        'oembed' => $module(controllers: ['oembed']),
        'toaster' => $module(['toaster']),
    ],
    'presets' => [
        'nova' => [
            'base' => [],
            'properties' => [],
            'aliases' => [],
            'contrast_pairs' => [],
            'sources' => array_map(
                static fn (string $name): array => [
                    'path' => "presets/nova/{$name}.css",
                    'modules' => [$name],
                ],
                $novaModules,
            ),
        ],
    ],
];
