<?php

$module = static fn (
    array $components = [],
    array $controllers = [],
    array $dependencies = [],
): array => compact('components', 'controllers', 'dependencies');

$novaModules = [
    'accordion',
    'alert',
    'alert-dialog',
    'text-shimmer',
    'attachment',
    'avatar',
    'back-to-top',
    'badge',
    'breadcrumb',
    'button-surfaces',
    'button-group',
    'card',
    'carousel',
    'choice-groups',
    'color-scheme-toggle',
    'drawer',
    'floating-presence',
    'dropdown',
    'empty-state',
    'field',
    'file',
    'file-upload',
    'hover-card',
    'icon',
    'control-wrappers',
    'clearable-input-layout',
    'text-controls',
    'checkable-controls',
    'clear-input-button',
    'input-group',
    'item',
    'kbd',
    'marker',
    'modal-overlay-layout',
    'dialog-backdrops',
    'modal',
    'overlay-motion',
    'multi-select',
    'sticky',
    'navbar',
    'pagination',
    'popover',
    'progress',
    'read-more',
    'reveal-surfaces',
    'read-more-reduced-motion',
    'rich-text',
    'scroll-progress',
    'select',
    'separators',
    'sheet',
    'side-panel',
    'sidebar',
    'skeleton',
    'slider',
    'spinner',
    'switch',
    'table',
    'tabs',
    'textarea',
    'timeago',
    'toggle-controls',
    'toggle-group',
    'oembed',
    'toaster',
    'tooltip',
];

return [
    'modules' => [
        'accordion' => $module(['accordion']),
        'alert' => $module(['alert']),
        'alert-dialog' => $module(['alert-dialog']),
        'text-shimmer' => $module(['attachment', 'skeleton']),
        'attachment' => $module(['attachment'], dependencies: ['button-surfaces']),
        'avatar' => $module(['avatar']),
        'back-to-top' => $module(['back-to-top']),
        'badge' => $module(['badge']),
        'breadcrumb' => $module(['breadcrumb']),
        'button-surfaces' => $module([
            'button',
            'attachment',
            'modal',
            'alert-dialog',
            'hover-card',
            'color-scheme.toggle',
            'back-to-top',
            'read-more',
        ]),
        'button-group' => $module(['button-group']),
        'card' => $module(['card']),
        'carousel' => $module(['carousel']),
        'choice-groups' => $module([
            'checkbox-group',
            'checkbox-group.item',
            'radio-group',
            'radio-group.item',
        ]),
        'color-scheme-toggle' => $module(['color-scheme.toggle']),
        'drawer' => $module(['drawer']),
        'floating-presence' => $module(
            ['dropdown', 'hover-card', 'popover', 'multi-select'],
            ['tooltip'],
        ),
        'dropdown' => $module(['dropdown']),
        'empty-state' => $module(['empty-state']),
        'field' => $module(['field', 'field.error', 'field.group', 'field.label']),
        'file' => $module(['file']),
        'file-upload' => $module(
            ['file-upload'],
            dependencies: ['attachment', 'empty-state', 'icon', 'progress', 'text-shimmer'],
        ),
        'hover-card' => $module(['hover-card']),
        'icon' => $module(['icon']),
        'control-wrappers' => $module(['input', 'textarea', 'file']),
        'clearable-input-layout' => $module(['input', 'multi-select']),
        'text-controls' => $module(['input', 'select']),
        'checkable-controls' => $module([
            'input',
            'checkbox',
            'checkbox-group',
            'checkbox-group.item',
            'radio-group',
            'radio-group.item',
        ]),
        'clear-input-button' => $module(['input', 'multi-select']),
        'input-group' => $module(['input-group']),
        'item' => $module(['item']),
        'kbd' => $module(['kbd']),
        'marker' => $module(['marker']),
        'modal-overlay-layout' => $module(['modal']),
        'dialog-backdrops' => $module(['modal', 'alert-dialog']),
        'modal' => $module(['modal']),
        'overlay-motion' => $module(['modal', 'alert-dialog', 'drawer', 'sheet', 'sidebar']),
        'multi-select' => $module(['multi-select'], dependencies: ['input-group']),
        'sticky' => $module(['sticky', 'navbar']),
        'navbar' => $module(['navbar', 'navbar.item']),
        'pagination' => $module(['pagination']),
        'popover' => $module(['popover']),
        'progress' => $module(['progress']),
        'read-more' => $module(['read-more']),
        'reveal-surfaces' => $module(['reveal', 'reveal.item', 'sidebar']),
        'read-more-reduced-motion' => $module(['read-more']),
        'rich-text' => $module(['rich-text']),
        'scroll-progress' => $module(['scroll-progress']),
        'select' => $module(['select']),
        'separators' => $module(['separator', 'item', 'button-group']),
        'sheet' => $module(['sheet']),
        'side-panel' => $module(['side-panel']),
        'sidebar' => $module(['sidebar']),
        'skeleton' => $module(['skeleton']),
        'slider' => $module(['slider']),
        'spinner' => $module(['spinner']),
        'switch' => $module(['switch']),
        'table' => $module(['table']),
        'tabs' => $module(['tabs']),
        'textarea' => $module(['textarea']),
        'timeago' => $module(['timeago']),
        'toggle-controls' => $module(['toggle', 'toggle-group', 'toggle-group.item']),
        'toggle-group' => $module(['toggle-group', 'toggle-group.item']),
        'oembed' => $module(controllers: ['oembed']),
        'toaster' => $module(controllers: ['toaster']),
        'tooltip' => $module(controllers: ['tooltip'], dependencies: ['floating-presence', 'kbd']),
    ],
    'presets' => [
        'nova' => [
            'sources' => array_map(
                static fn (string $name): array => [
                    'path' => "presets/nova/{$name}.css",
                    'modules' => [$name],
                ],
                $novaModules,
            ),
        ],
    ],
];
