<?php

use Emaia\LaravelHotwire\Support\GeneratedStyleBundle;
use Emaia\LaravelHotwire\Support\PresetSource;

function generatedBundleSource(string $css = '[data-slot="badge"] { color: red; }'): PresetSource
{
    return new PresetSource(
        'nova',
        ['foundation.css'],
        [$css],
        ['presets/nova/badge.css'],
    );
}

it('renders a component-only v2 plan with a verifiable artifact hash', function () {
    $bundle = new GeneratedStyleBundle;
    $content = $bundle->render(
        'resources/css/hotwire.css',
        generatedBundleSource(),
        'nova',
        ['modal', 'badge', 'badge'],
        ['modal', 'badge', 'badge'],
    );
    $plan = $bundle->planFromContent($content);

    expect($plan)
        ->toMatchArray([
            'version' => 2,
            'preset' => 'nova',
            'components' => ['badge', 'modal'],
            'modules' => ['badge', 'modal'],
        ])
        ->not->toHaveKey('controllers')
        ->and($plan['hash'])->toMatch('/^[a-f0-9]{64}$/')
        ->and($bundle->hashMatches($content))->toBeTrue();
});

it('normalizes line endings while detecting edits anywhere in a v2 artifact', function () {
    $bundle = new GeneratedStyleBundle;
    $content = $bundle->render(
        'resources/css/hotwire.css',
        generatedBundleSource(),
        'nova',
        ['badge'],
        ['badge'],
    );

    expect($bundle->hashMatches(str_replace("\n", "\r\n", $content)))->toBeTrue()
        ->and($bundle->hashMatches(str_replace('color: red', 'color: blue', $content)))->toBeFalse();
});

it('continues to read canonical v1 plans without treating them as hash-verifiable', function () {
    $bundle = new GeneratedStyleBundle;
    $content = implode("\n", [
        '/* @hotwire-package */',
        '/* hotwire-preset-bundle-plan: {"version":1,"preset":"nova","components":["badge"],"controllers":["tooltip"],"modules":["badge"]} */',
        '/* Generated by `php artisan hotwire:bundle-preset`. Regenerate instead of editing. */',
        '',
    ]);

    expect($bundle->planFromContent($content))
        ->toBe([
            'version' => 1,
            'preset' => 'nova',
            'components' => ['badge'],
            'controllers' => ['tooltip'],
            'modules' => ['badge'],
        ])
        ->and($bundle->hashMatches($content))->toBeFalse();
});
