<?php

use Emaia\LaravelHotwire\Registry\HotwireRegistry;
use Emaia\LaravelHotwire\Support\ControllerLoadPlan;
use Emaia\LaravelHotwire\Support\LoaderStub;
use Illuminate\Filesystem\Filesystem;

beforeEach(function () {
    HotwireRegistry::reset();
    $this->registry = HotwireRegistry::make();
    $this->files = new Filesystem;
    $this->controllersDir = sys_get_temp_dir().'/hwc-loader-stub-'.uniqid();
    $this->files->makeDirectory($this->controllersDir, 0755, true);
});

afterEach(function () {
    $this->files->deleteDirectory($this->controllersDir);
});

// --- generate() ---

it('emits the auto-generated marker as the first line', function () {
    $content = LoaderStub::generate($this->registry);

    expect($content)->toStartWith('// AUTO-GENERATED by hotwire:install');
});

it('produces a single-string glob with no exclusions in default mode', function () {
    $content = LoaderStub::generate($this->registry);

    expect($content)
        ->toContain('"../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js"')
        ->not->toContain('"!**/');
});

it('excludes every com-dep controller in core-only mode (empty opt-in)', function () {
    $content = LoaderStub::generate($this->registry, []);

    expect($content)
        ->toContain('"!**/carousel_controller.js"')
        ->toContain('"!**/chart_controller.js"')
        ->toContain('"!**/dropdown_controller.js"')
        ->toContain('"!**/map_controller.js"')
        ->toContain('"!**/multi_select_controller.js"')
        ->toContain('"!**/rich_text_controller.js"')
        ->toContain('"!**/tooltip_controller.js"');
});

it('keeps the opted-in com-dep controllers and excludes the rest', function () {
    $content = LoaderStub::generate($this->registry, ['carousel', 'chart']);

    expect($content)
        ->not->toContain('"!**/carousel_controller.js"')
        ->not->toContain('"!**/chart_controller.js"')
        ->toContain('"!**/dropdown_controller.js"')
        ->toContain('"!**/map_controller.js"')
        ->toContain('"!**/multi_select_controller.js"')
        ->toContain('"!**/rich_text_controller.js"');
});

it('never excludes zero-dep controllers', function () {
    $content = LoaderStub::generate($this->registry, []);

    // modal, auto-submit, etc. are zero-dep
    expect($content)
        ->not->toContain('"!**/modal_controller.js"')
        ->not->toContain('"!**/auto_submit_controller.js"');
});

it('alphabetises the exclusion list', function () {
    $content = LoaderStub::generate($this->registry, []);

    preg_match_all('/"!\*\*\/([a-z0-9_-]+_controller\.js)"/', $content, $matches);
    $exclusions = $matches[1];
    $sorted = $exclusions;
    sort($sorted);

    expect($exclusions)->toBe($sorted);
});

it('emits mixed lazy and eager registries using lazy-loader v2 precedence', function () {
    file_put_contents($this->controllersDir.'/navigation_controller.ts', 'export default class {}');

    $plan = ControllerLoadPlan::make(
        $this->files,
        $this->registry,
        $this->controllersDir,
        eagerControllers: ['navigation', 'modal'],
    );
    $content = LoaderStub::generateFromPlan($plan);

    expect($content)
        ->toContain('const packageControllers = import.meta.glob(')
        ->toContain('const eagerPackageControllers = import.meta.glob(')
        ->toContain('"../../../vendor/emaia/laravel-hotwire/resources/js/controllers/modal_controller.js"')
        ->toContain('const userControllers = import.meta.glob(')
        ->toContain('const eagerUserControllers = import.meta.glob(')
        ->toContain('"./navigation_controller.ts"')
        ->toContain('{ eager: true }')
        ->toContain('...packageControllers,')
        ->toContain('...eagerPackageControllers,')
        ->toContain('...userControllers,')
        ->toContain('...eagerUserControllers,');

    expect(strpos($content, '...packageControllers,'))
        ->toBeLessThan(strpos($content, '...eagerPackageControllers,'));
    expect(strpos($content, '...eagerPackageControllers,'))
        ->toBeLessThan(strpos($content, '...userControllers,'));
    expect(strpos($content, '...userControllers,'))
        ->toBeLessThan(strpos($content, '...eagerUserControllers,'));
});

it('excludes eager paths from their lazy globs', function () {
    file_put_contents($this->controllersDir.'/navigation_controller.js', 'export default class {}');

    $content = LoaderStub::generate(
        $this->registry,
        eagerControllers: ['navigation', 'modal'],
        appControllersPath: $this->controllersDir,
    );

    expect($content)
        ->toContain('"!./navigation_controller.js"')
        ->toContain('"!../../../vendor/emaia/laravel-hotwire/resources/js/controllers/modal_controller.js"');
});

it('applies exclusions when globBlock receives an explicit pattern list', function () {
    $method = new ReflectionMethod(LoaderStub::class, 'globBlock');
    $content = $method->invoke(null, 'controllers', ['./a.js'], ['./excluded.js']);

    expect($content)
        ->toContain('"./a.js"')
        ->toContain('"./excluded.js"');
});

it('quotes a single glob pattern as JavaScript JSON', function () {
    $method = new ReflectionMethod(LoaderStub::class, 'globBlock');
    $pattern = './quoted"\\controller.js';
    $content = $method->invoke(null, 'controllers', $pattern);

    expect($content)->toContain(json_encode($pattern, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
});

it('keeps shadowed package fallbacks and application registries last', function () {
    file_put_contents($this->controllersDir.'/modal_controller.ts', 'export default class {}');

    $content = LoaderStub::generate(
        $this->registry,
        eagerControllers: ['modal'],
        appControllersPath: $this->controllersDir,
    );

    expect($content)
        ->not->toContain('"!../../../vendor/emaia/laravel-hotwire/resources/js/controllers/modal_controller.js"')
        ->toContain('"!./modal_controller.ts"')
        ->toContain('"./modal_controller.ts"');
});

// --- isAutoGenerated() ---

it('detects an auto-generated stub via its marker', function () {
    $content = LoaderStub::generate($this->registry);

    expect(LoaderStub::isAutoGenerated($content))->toBeTrue();
});

it('treats a hand-written stub (no marker) as not auto-generated', function () {
    $content = <<<'JS'
        import { Stimulus } from "../libs/stimulus";
        // user-written without the marker
        JS;

    expect(LoaderStub::isAutoGenerated($content))->toBeFalse();
});

it('ignores leading whitespace when detecting the marker', function () {
    $content = "\n\n".LoaderStub::generate($this->registry);

    expect(LoaderStub::isAutoGenerated($content))->toBeTrue();
});

// --- includedComDepControllers() ---

it('reports every com-dep controller as included when no exclusions are present', function () {
    $content = LoaderStub::generate($this->registry);

    $included = LoaderStub::includedComDepControllers($content, $this->registry);

    expect($included)
        ->toContain('carousel')
        ->toContain('chart')
        ->toContain('dropdown')
        ->toContain('map')
        ->toContain('multi-select')
        ->toContain('rich-text')
        ->toContain('tooltip');
});

it('returns only the opted-in com-dep controllers as included', function () {
    $content = LoaderStub::generate($this->registry, ['carousel']);

    $included = LoaderStub::includedComDepControllers($content, $this->registry);

    expect($included)
        ->toContain('carousel')
        ->not->toContain('chart')
        ->not->toContain('map');
});

it('returns an empty list in core-only mode', function () {
    $content = LoaderStub::generate($this->registry, []);

    expect(LoaderStub::includedComDepControllers($content, $this->registry))->toBe([]);
});

it('returns null for a hand-written (non-auto-generated) stub', function () {
    expect(LoaderStub::includedComDepControllers('// custom user file', $this->registry))->toBeNull();
});

// --- plan metadata ---

it('emits and reads machine-readable plan metadata', function () {
    file_put_contents($this->controllersDir.'/navigation_controller.ts', 'export default class {}');

    $content = LoaderStub::generate(
        $this->registry,
        ['carousel'],
        ['navigation'],
        ['carousel'],
        $this->controllersDir,
    );
    $policy = LoaderStub::policyFromContent($content, $this->registry);

    expect($content)->toContain('// hotwire-loader-plan: {')
        ->and($policy)->not->toBeNull()
        ->and($policy->includedComDepControllers)->toBe(['carousel'])
        ->and($policy->preloadControllers)->toBe(['navigation'])
        ->and($policy->eagerControllers)->toBe(['carousel'])
        ->and($policy->eagerControllerPaths)->toBe([
            'carousel' => '../../../vendor/emaia/laravel-hotwire/resources/js/controllers/carousel_controller.js',
        ])
        ->and(LoaderStub::includedComDepControllers($content, $this->registry))->toBe(['carousel']);
});

it('preserves default include-all dependency mode in metadata', function () {
    $policy = LoaderStub::policyFromContent(
        LoaderStub::generate($this->registry),
        $this->registry,
    );

    expect($policy->includeAllComDepControllers)->toBeTrue();
});

it('records preload selections without emitting runtime imports', function () {
    file_put_contents($this->controllersDir.'/navigation_controller.ts', 'export default class {}');

    $content = LoaderStub::generate(
        $this->registry,
        preloadControllers: ['navigation'],
        appControllersPath: $this->controllersDir,
    );

    expect($content)
        ->toContain('"preloadControllers":["navigation"]')
        ->not->toContain('loadController(')
        ->not->toContain('eagerUserControllers');
});

it('falls back to negative globs when an existing generated stub has no metadata', function () {
    $legacy = <<<'JS'
        // AUTO-GENERATED by hotwire:install — DO NOT EDIT MANUALLY.
        const packageControllers = import.meta.glob([
            "../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js",
            "!**/carousel_controller.js",
            "!**/chart_controller.js",
        ]);
        JS;

    $policy = LoaderStub::policyFromContent($legacy, $this->registry);

    expect($policy)->not->toBeNull()
        ->and($policy->includedComDepControllers)
        ->not->toContain('carousel')
        ->not->toContain('chart')
        ->and($policy->preloadControllers)->toBe([])
        ->and($policy->eagerControllers)->toBe([]);
});

it('preserves include-all mode for a metadata-less generated stub without exclusions', function () {
    $legacy = <<<'JS'
        // AUTO-GENERATED by hotwire:install — DO NOT EDIT MANUALLY.
        const packageControllers = import.meta.glob(
            "../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js"
        );
        JS;

    expect(LoaderStub::policyFromContent($legacy, $this->registry)->includeAllComDepControllers)->toBeTrue();
});
