<?php

use Emaia\LaravelHotwire\Registry\HotwireRegistry;
use Emaia\LaravelHotwire\Support\LoaderStub;

beforeEach(function () {
    HotwireRegistry::reset();
    $this->registry = HotwireRegistry::make();
});

// --- generate() ---

it('emits the auto-generated marker as the first line', function () {
    $content = LoaderStub::generate($this->registry);

    expect($content)->toStartWith('// AUTO-GENERATED by hotwire:install');
});

it('produces a single-string glob with no exclusions in default mode', function () {
    $content = LoaderStub::generate($this->registry);

    expect($content)
        ->toContain('"../../../vendor/emaia/laravel-hotwire/resources/js/controllers/**/*_controller.js"')
        ->not->toContain('"!**/');
});

it('excludes every com-dep controller in core-only mode (empty opt-in)', function () {
    $content = LoaderStub::generate($this->registry, []);

    expect($content)
        ->toContain('"!**/carousel_controller.js"')
        ->toContain('"!**/chart_controller.js"')
        ->toContain('"!**/map_controller.js"')
        ->toContain('"!**/rich_text_controller.js"')
        ->toContain('"!**/tooltip_controller.js"');
});

it('keeps the opted-in com-dep controllers and excludes the rest', function () {
    $content = LoaderStub::generate($this->registry, ['carousel', 'chart']);

    expect($content)
        ->not->toContain('"!**/carousel_controller.js"')
        ->not->toContain('"!**/chart_controller.js"')
        ->toContain('"!**/map_controller.js"')
        ->toContain('"!**/rich_text_controller.js"');
});

it('never excludes zero-dep controllers', function () {
    $content = LoaderStub::generate($this->registry, []);

    // modal, dropdown, auto-submit, etc. are zero-dep
    expect($content)
        ->not->toContain('"!**/modal_controller.js"')
        ->not->toContain('"!**/dropdown_controller.js"')
        ->not->toContain('"!**/auto_submit_controller.js"');
});

it('alphabetises the exclusion list', function () {
    $content = LoaderStub::generate($this->registry, []);

    preg_match_all('/"!\*\*\/([a-z0-9_-]+_controller\.js)"/', $content, $matches);
    $exclusions = $matches[1];
    $sorted = $exclusions;
    sort($sorted);

    expect($exclusions)->toBe($sorted);
});

// --- isAutoGenerated() ---

it('detects an auto-generated stub via its marker', function () {
    $content = LoaderStub::generate($this->registry);

    expect(LoaderStub::isAutoGenerated($content))->toBeTrue();
});

it('treats a hand-written stub (no marker) as not auto-generated', function () {
    $content = <<<'JS'
        import { Stimulus } from "../libs/stimulus";
        // user-written without the marker
        JS;

    expect(LoaderStub::isAutoGenerated($content))->toBeFalse();
});

it('ignores leading whitespace when detecting the marker', function () {
    $content = "\n\n".LoaderStub::generate($this->registry);

    expect(LoaderStub::isAutoGenerated($content))->toBeTrue();
});

// --- includedComDepControllers() ---

it('reports every com-dep controller as included when no exclusions are present', function () {
    $content = LoaderStub::generate($this->registry);

    $included = LoaderStub::includedComDepControllers($content, $this->registry);

    expect($included)
        ->toContain('carousel')
        ->toContain('chart')
        ->toContain('map')
        ->toContain('rich-text')
        ->toContain('tooltip');
});

it('returns only the opted-in com-dep controllers as included', function () {
    $content = LoaderStub::generate($this->registry, ['carousel']);

    $included = LoaderStub::includedComDepControllers($content, $this->registry);

    expect($included)
        ->toContain('carousel')
        ->not->toContain('chart')
        ->not->toContain('map');
});

it('returns an empty list in core-only mode', function () {
    $content = LoaderStub::generate($this->registry, []);

    expect(LoaderStub::includedComDepControllers($content, $this->registry))->toBe([]);
});

it('returns null for a hand-written (non-auto-generated) stub', function () {
    expect(LoaderStub::includedComDepControllers('// custom user file', $this->registry))->toBeNull();
});
