<?php

use Emaia\LaravelHotwire\Support\PackageMarker;
use Illuminate\Support\Facades\File;

beforeEach(function () {
    $this->appBase = isolateAppPaths();
    $this->output = resource_path('css/hotwire.css');
});

afterEach(function () {
    releaseIsolatedAppPaths($this->appBase);
});

it('generates a marked selective bundle with shared foundation imports', function () {
    $this->artisan('hotwire:styles --components=modal --no-interaction')
        ->expectsOutputToContain('resources/css/hotwire.css')
        ->assertSuccessful();

    $css = File::get($this->output);

    expect($css)
        ->toStartWith('/* '.PackageMarker::TAG.' */')
        ->toContain('@import "../../vendor/emaia/laravel-hotwire/resources/css/tokens.css";')
        ->toContain('@import "../../vendor/emaia/laravel-hotwire/resources/css/custom-variants.css";')
        ->toContain('@import "../../vendor/emaia/laravel-hotwire/resources/css/structural.css";')
        ->toContain('[data-slot="modal-panel"]')
        ->toContain('[data-slot="modal-trigger"]')
        ->not->toContain('[data-slot="carousel"]')
        ->toEndWith("\n");
});

it('includes visual controllers mounted by selected components', function () {
    $this->artisan('hotwire:styles --components=toaster --no-interaction')->assertSuccessful();

    expect(File::get($this->output))
        ->toContain('[data-slot="toast"]')
        ->not->toContain('[data-slot="modal-panel"]');
});

it('accepts repeated manual component and controller inclusions', function () {
    $this->artisan('hotwire:styles --components=badge --include=modal --include=tooltip --no-interaction')
        ->assertSuccessful();

    expect(File::get($this->output))
        ->toContain('[data-slot="badge"]')
        ->toContain('[data-slot="modal-panel"]')
        ->toContain('[data-slot="tooltip"]')
        ->not->toContain('[data-slot="carousel"]');
});

it('parses comma-separated components and adjusts imports for a custom output depth', function () {
    $output = resource_path('css/generated/front.css');

    $this->artisan('hotwire:styles --components=badge,modal --output=resources/css/generated/front.css --no-interaction')
        ->assertSuccessful();

    expect(File::get($output))
        ->toContain('@import "../../../vendor/emaia/laravel-hotwire/resources/css/tokens.css";')
        ->toContain('[data-slot="badge"]')
        ->toContain('[data-slot="modal-panel"]');
});

it('fails before writing for unknown presets and selections', function (string $command, string $message) {
    $this->artisan($command)
        ->expectsOutputToContain($message)
        ->assertFailed();

    expect(File::exists($this->output))->toBeFalse();
})->with([
    'preset' => ['hotwire:styles --preset=missing --components=modal --no-interaction', 'Unknown preset "missing"'],
    'component' => ['hotwire:styles --components=modla --no-interaction', 'Unknown component "modla"'],
    'include' => ['hotwire:styles --components=modal --include=missing --no-interaction', 'Unknown component or controller "missing"'],
]);

it('requires an explicit selection', function () {
    $this->artisan('hotwire:styles --no-interaction')
        ->expectsOutputToContain('Select at least one component or controller')
        ->assertFailed();

    expect(File::exists($this->output))->toBeFalse();
});

it('requires force to replace a generated bundle', function () {
    $this->artisan('hotwire:styles --components=badge --no-interaction')->assertSuccessful();

    $this->artisan('hotwire:styles --components=modal --no-interaction')
        ->expectsOutputToContain('Use --force to overwrite')
        ->assertFailed();

    expect(File::get($this->output))->toContain('[data-slot="badge"]');

    $this->artisan('hotwire:styles --components=modal --force --no-interaction')->assertSuccessful();

    expect(File::get($this->output))
        ->toContain('[data-slot="modal-panel"]')
        ->not->toContain('[data-slot="badge"]');
});

it('never replaces a user-owned output even with force', function () {
    File::ensureDirectoryExists(dirname($this->output));
    File::put($this->output, '/* application-owned */');

    $this->artisan('hotwire:styles --components=modal --force --no-interaction')
        ->expectsOutputToContain('not generated by Laravel Hotwire')
        ->assertFailed();

    expect(File::get($this->output))->toBe('/* application-owned */');
});

it('rejects output paths outside the application', function () {
    $this->artisan('hotwire:styles --components=modal --output=../hotwire.css --no-interaction')
        ->expectsOutputToContain('Output must be a relative path inside the application')
        ->assertFailed();

    expect(File::exists(dirname($this->appBase).'/hotwire.css'))->toBeFalse();
});
