import { beforeAll, describe, expect, test } from "bun:test";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import baselines from "./preset_build_baselines.json";
import {
    buildCssContract,
    compileCssFixture,
    disableAutomaticSources,
    measurementRows,
    minifyCssWithVite,
    packageSourceEntrypoint,
    replacePresetImport,
    resolveBaselines,
} from "../../scripts/css_build_contract.js";

const slotSelector = (slot) => new RegExp(`\\[data-slot=(?:["'])?${slot}(?:["'])?\\]`);
const attributeValueSelector = (attribute, value) => new RegExp(`\\[${attribute}=(?:["'])?${value}(?:["'])?\\]`);
const carouselMechanic = /\[data-carousel-container\]/;
const automaticSourceUtility = String.raw`.w-\[811px\]`;
const expressivenessFixturePath = new URL("../Fixtures/css/preset_expressiveness.css", import.meta.url);
const applicationPresetFixturePath = new URL(
    "../Fixtures/css/application-preset/resources/css/presets",
    import.meta.url,
);
const packageSources = [
    {
        directive: '@source "../../vendor/emaia/laravel-hotwire/resources/views/**/*.blade.php";',
        utility: String.raw`.min-h-\[137px\]`,
    },
    {
        directive: '@source "../../vendor/emaia/laravel-hotwire/src/**/*.php";',
        utility: String.raw`.max-w-\[913px\]`,
    },
    {
        directive: '@source "../../vendor/emaia/laravel-hotwire/resources/js/**/*.js";',
        utility: String.raw`.z-\[31415\]`,
    },
];

let contract;
let productionNovaCss;

beforeAll(async () => {
    contract = await buildCssContract();
    productionNovaCss = await minifyCssWithVite(contract.outputs.presets.nova);
});

describe("public CSS presets", () => {
    test("compile every discovered preset through an installed-app entrypoint", () => {
        expect(Object.keys(contract.outputs.presets).length).toBeGreaterThan(0);

        for (const css of Object.values(contract.outputs.presets)) {
            expect(css).toContain("--background:");
            expect(css).toContain("--radius:");
            expect(css).toMatch(slotSelector("button"));
            expect(css).toMatch(carouselMechanic);
            expect(css).toContain(".hidden{display:none}");
            expect(css).toContain(".overflow-hidden{overflow:hidden}");
        }
    });

    test("compiles a generated selective bundle for every discovered preset", () => {
        expect(Object.keys(contract.outputs.selectives)).toEqual(Object.keys(contract.outputs.presets));

        for (const [preset, css] of Object.entries(contract.outputs.selectives)) {
            const source = contract.sources.selectives[preset];

            expect(source).toStartWith("/* @hotwire-package */");
            expect(source).toContain('@import "../../../vendor/emaia/laravel-hotwire/resources/css/tokens.css";');
            expect(source).toMatch(slotSelector("button"));
            expect(source).toMatch(slotSelector("card"));
            expect(source).toMatch(slotSelector("tooltip"));

            expect(css).toContain("--background:");
            expect(css).toContain("--radius:");
            expect(css).toMatch(slotSelector("button"));
            expect(css).toMatch(slotSelector("card"));
            expect(css).toMatch(carouselMechanic);
            for (const { utility } of packageSources) {
                expect(css).toContain(utility);
            }
        }

        expect(contract.sources.selectives.nova).not.toMatch(slotSelector("badge"));
        expect(contract.outputs.selectives.nova).not.toMatch(slotSelector("badge"));
    });

    test("compiles an application-owned clone of every discovered preset", () => {
        expect(Object.keys(contract.outputs.clones)).toEqual(Object.keys(contract.outputs.presets));

        for (const [preset, css] of Object.entries(contract.outputs.clones)) {
            const source = contract.sources.clones[preset];

            expect(source).toContain('@import "../../../vendor/emaia/laravel-hotwire/resources/css/tokens.css";');
            expect(source).toContain('@import "../../../vendor/emaia/laravel-hotwire/resources/css/structural.css";');
            expect(source).not.toContain(`@import "./${preset}/`);
            expect(css).toContain("--background:");
            expect(css).toMatch(slotSelector("button"));
            expect(css).toMatch(carouselMechanic);
        }
    });

    test("compiles the blank application preset scaffold generated by make-preset", () => {
        const css = contract.outputs.blankScaffold;
        const source = contract.sources.blankScaffold;

        expect(source).toContain('@import "../../../vendor/emaia/laravel-hotwire/resources/css/tokens.css";');
        expect(source).toContain('@import "../../../vendor/emaia/laravel-hotwire/resources/css/structural.css";');
        expect(source).toMatch(/\[data-slot="button"\] \{\}/);
        expect(css).toContain("--background:");
        expect(css).toMatch(carouselMechanic);
    });

    test("carries the Textarea counter slot through presets and application scaffolds", () => {
        for (const css of Object.values(contract.outputs.presets)) {
            expect(css).toMatch(slotSelector("textarea-counter"));
        }

        for (const source of Object.values(contract.sources.clones)) {
            expect(source).toMatch(slotSelector("textarea-counter"));
        }

        expect(contract.sources.blankScaffold).toMatch(/\[data-slot="textarea-counter"\] \{\}/);
    });

    test("compiles shared forced-colors and print control fallbacks into every bundle", () => {
        for (const css of [
            ...Object.values(contract.outputs.presets),
            ...Object.values(contract.outputs.selectives),
            ...Object.values(contract.outputs.clones),
            contract.outputs.blankScaffold,
        ]) {
            expect(css).toContain("@media (forced-colors:active)");
            expect(css).toContain("@media print");
            expect(css).toMatch(slotSelector("switch"));
            expect(css).toMatch(slotSelector("slider"));
            expect(css).toMatch(slotSelector("multi-select-indicator"));
            expect(css).toMatch(slotSelector("progress-indicator"));
            expect(css).toContain("forced-color-adjust:none");
        }
    });

    test("preserves attribute-backed RTL selectors through Vite production minification", () => {
        expect(productionNovaCss).toMatch(/\[data-slot=switch\][^{]*\[dir=rtl\][^{]*:checked:before\{/);
        expect(productionNovaCss).toMatch(
            /\[data-slot=slider\]\[data-orientation=horizontal\][^{]*\[dir=rtl\][^{]*::-webkit-slider-runnable-track\{[^}]*linear-gradient\(to left/,
        );
        expect(productionNovaCss).toMatch(
            /\[data-slot=side-panel\]\[data-side=left\][^{]*\[dir=rtl\][^{]*\{flex-direction:row-reverse\}/,
        );
        expect(productionNovaCss).toMatch(
            /\[data-slot=side-panel\]\[data-side=right\][^{]*\[dir=rtl\][^{]*\{flex-direction:row\}/,
        );
    });

    test("preserves customizable structural motion timing in the compiled Nova preset", () => {
        expect(productionNovaCss).toContain("--read-more-motion-duration:.5s");
        expect(productionNovaCss).toContain("--read-more-motion-easing:ease-in-out");
        expect(productionNovaCss).toContain("--side-panel-motion-duration:.2s");
        expect(productionNovaCss).toContain("--side-panel-content-motion-duration:.15s");
        expect(productionNovaCss).toContain("--side-panel-motion-easing:ease-in-out");
        expect(productionNovaCss).toContain(
            "transition:max-block-size var(--read-more-motion-duration,.5s) var(--read-more-motion-easing,ease-in-out)",
        );
        expect(productionNovaCss).toContain(
            "transition:inline-size var(--side-panel-motion-duration,.2s) var(--side-panel-motion-easing,ease-in-out)",
        );
        for (const selector of [
            String.raw`\[data-slot=side-panel\]:before`,
            String.raw`\[data-slot=side-panel-trigger\]`,
            String.raw`\[data-slot=side-panel-trigger-icon\]`,
        ]) {
            expect(productionNovaCss).toMatch(
                new RegExp(
                    `${selector}\\{[^}]*transition-duration:var\\(--side-panel-motion-duration\\);transition-timing-function:var\\(--side-panel-motion-easing\\)\\}`,
                ),
            );
        }
    });

    test("reports raw and gzip sizes against non-blocking baselines", () => {
        expect(contract.measurements.toolchain.tailwindcss).toMatch(/^4\./);
        expect(contract.measurements.toolchain.cli).toMatch(/^4\./);
        expect(baselines.toolchain.tailwindcss).toMatch(/^4\./);
        expect(baselines.toolchain.cli).toMatch(/^4\./);

        for (const measurements of [
            ...Object.values(contract.measurements.presets),
            ...Object.values(contract.measurements.selectives),
            ...Object.values(baselines.presets),
            ...Object.values(baselines.selectives),
        ]) {
            expect(measurements.rawBytes).toBeGreaterThan(0);
            expect(measurements.gzipBytes).toBeGreaterThan(0);
        }
    });

    test("compiles runtime utilities supplied only by the structural safelist", async () => {
        const css = await compileCssFixture(`
            @import "tailwindcss" source(none);
            @import "../../vendor/emaia/laravel-hotwire/resources/css/structural.css";
        `);

        expect(css).toContain(".hidden{display:none}");
        expect(css).toContain(".overflow-hidden{overflow:hidden}");
    });

    test("can compile an installed-app fixture without production minification", async () => {
        const css = await compileCssFixture(
            `
                @import "tailwindcss" source(none);
                .unminified-probe { color: red; }
            `,
            { minify: false },
        );

        expect(css).toContain(".unminified-probe {");
        expect(css).toContain("  color: red;");
    });

    test("compiles the reusable preset expressiveness fixture", async () => {
        const fixture = await readFile(expressivenessFixturePath, "utf8");
        const css = await compileCssFixture(`
            @import "tailwindcss";
            @import "../../vendor/emaia/laravel-hotwire/resources/css/tokens.css";

            ${fixture}
        `);

        for (const personality of ["vega", "mira", "sera", "luma"]) {
            expect(css).toMatch(attributeValueSelector("data-preset-fixture", personality));
        }

        for (const slot of ["button", "card", "input", "select", "alert", "modal-panel"]) {
            expect(css).toMatch(slotSelector(slot));
        }

        expect(css).toContain("@media (prefers-reduced-motion:reduce)");
        expect(css).toMatch(attributeValueSelector("aria-invalid", "true"));
        expect(css).toMatch(/:disabled/);
    });

    test("compiles the synthetic application preset through its public entrypoint", async () => {
        const css = await compileCssFixture(
            `
                @import "tailwindcss";
                @import "./presets/constellation.css";
            `,
            {
                setup: async (directory) => {
                    await cp(applicationPresetFixturePath, join(directory, "resources/css/presets"), {
                        recursive: true,
                    });
                },
            },
        );

        for (const slot of ["fixture-panel", "fixture-action", "fixture-status"]) {
            expect(css).toMatch(slotSelector(slot));
        }

        expect(css).not.toMatch(/@(import|apply)\b/);
    });

    test("requires every explicit package source to discover its vendor candidates", async () => {
        const fixture = packageSourceEntrypoint();

        for (const { directive, utility } of packageSources) {
            const withoutSource = fixture.replace(`${directive}\n`, "");
            expect(withoutSource).not.toBe(fixture);

            const css = await compileCssFixture(withoutSource);
            expect(css).not.toContain(utility);
        }
    });

    test("disables automatic sources for exactly one Tailwind import", async () => {
        expect(disableAutomaticSources('@import "tailwindcss";')).toBe('@import "tailwindcss" source(none);');
        expect(disableAutomaticSources('@import "tailwindcss" theme(static);')).toBe(
            '@import "tailwindcss" source(none) theme(static);',
        );
        expect(disableAutomaticSources('@import "tailwindcss" source(none);')).toBe(
            '@import "tailwindcss" source(none);',
        );
        expect(() => disableAutomaticSources('@import "./app.css";')).toThrow(/exactly one Tailwind import/);
        expect(() => disableAutomaticSources('@import "tailwindcss";\n@import "tailwindcss";')).toThrow(
            /exactly one Tailwind import/,
        );
        expect(() => disableAutomaticSources('@import "tailwindcss" source("./app");')).toThrow(/incompatible source/);

        const css = await compileCssFixture('@import "tailwindcss" theme(static);');
        expect(css).not.toContain(automaticSourceUtility);
        for (const { utility } of packageSources) {
            expect(css).not.toContain(utility);
        }
    });

    test("requires exactly one public preset import in the app stub", () => {
        const presetImport = '@import "../../vendor/emaia/laravel-hotwire/resources/css/presets/nova.css";';

        expect(replacePresetImport(presetImport, "bloom")).toContain("presets/bloom.css");
        expect(() => replacePresetImport('@import "tailwindcss";', "bloom")).toThrow(
            /exactly one public preset import/,
        );
        expect(() => replacePresetImport(`${presetImport}\n${presetImport}`, "bloom")).toThrow(
            /exactly one public preset import/,
        );
    });

    test("rewrites missing or malformed baselines in update mode", async () => {
        const directory = await mkdtemp(join(tmpdir(), "hotwire-css-baseline-"));
        const path = join(directory, "baselines.json");

        try {
            expect(
                await resolveBaselines(contract.measurements, {
                    path,
                    update: true,
                }),
            ).toEqual(contract.measurements);

            await writeFile(path, "not json");

            expect(
                await resolveBaselines(contract.measurements, {
                    path,
                    update: true,
                }),
            ).toEqual(contract.measurements);
        } finally {
            await rm(directory, { recursive: true, force: true });
        }
    });

    test("reports zero deltas when optional baseline entries are absent", () => {
        const rows = measurementRows(contract.measurements, {
            toolchain: {},
            presets: {},
        });

        expect(rows.find(({ build }) => build.startsWith("selective:"))).toMatchObject({
            rawDelta: 0,
            gzipDelta: 0,
        });
    });

    test("fails when Tailwind cannot resolve a utility", async () => {
        await expect(
            compileCssFixture(`
                @import "tailwindcss";

                [data-slot="broken"] {
                    @apply hotwire-utility-that-does-not-exist;
                }
            `),
        ).rejects.toThrow();
    });

    test("fails when an imported stylesheet is missing", async () => {
        await expect(
            compileCssFixture(`
                @import "tailwindcss";
                @import "./missing-stylesheet.css";
            `),
        ).rejects.toThrow();
    });
});
